name: Fetch Uno Calculator Snap

on:
  workflow_dispatch:

jobs:
  fetch-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Install squashfs-tools
        run: sudo apt update && sudo apt install -y squashfs-tools

      - name: Download Uno Calculator Snap
        run: |
          snap download uno-calculator
          mkdir extracted
          unsquashfs -d extracted uno-calculator.snap

      - name: Zip extracted contents
        run: zip -r Release.zip extracted/

      - name: Create GitHub Release using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create uno-calculator-release Release.zip \
            --title "Uno Calculator Extracted" \
            --notes "This release contains the extracted contents of the Uno Calculator Snap package."
